#pragma once


// Define 8bit color constants
#define COLOR_BLACK 0
#define COLOR_WHITE 1
#define COLOR_SKY 2
#define COLOR_GND 3
#define COLOR_YELLOW 4
#define COLOR_RED 5
#define COLOR_GREEN 9

#define UI_BACKGROUND_COLOR 6
#define UI_TOP_BAR_DIV_LINE_COLOR 7
#define UI_OUTER_CIRCLE_COLOR 8
#define UI_TOP_BAR_COLOR COLOR_BLACK
#define UI_INNER_CIRCLE_COLOR COLOR_WHITE
#define UI_MY_AIRCRAFT_COLOR COLOR_RED

#define COLOR_TRANSPARENT 15

// #define COLOR_BLACK TFT_BLACK
// #define COLOR_WHITE TFT_WHITE
// #define COLOR_SKY 0x02B5
// #define COLOR_GND 0x5140
// #define COLOR_YELLOW 0xEE4C
// #define COLOR_RED TFT_RED
// #define COLOR_TRANSPARENT TFT_TRANSPARENT
